services:
  - type: web
    name: gofile-direct-link
    env: php
    plan: free
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000 index.php"
    healthCheckPath: "/"
    timeoutInSeconds: 300
